### PR TITLE
Add missing closing bracket

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Looks like @kghbln eated the bracket!

**Comment by kghbln** [comment]
:P Thanks for fixing.

**Comment by JeroenDeDauw** [comment]
I suppose you need to eat a lot of brackets before you look like 

eated-lots-of-brackets

**Comment by mwjames** [comment]
You gotta be joking ... マジ...

**Comment by JeroenDeDauw** [comment]
23062_original

**Comment by kghbln** [comment]
OMG, I guess we are starting to get in trouble with tribbles :)

**Comment by JeroenDeDauw** [comment]
Then perhaps we should switch to trials and tribble-ations?

**Pull request merged**
