### PR TITLE
Change depreciated wfMsgExt to wfMessage

### PR DESCRIPTION
**Pull request by kghbln**
Addresses issue https://github.com/SemanticMediaWiki/SemanticWatchlist/issues/10. Special thanks go to Siebrand for his suggestions and help!

### CODE REVIEW

**Comment by mwjames** [comment]
We currently have no tests here, so I trust your judgement (as we don't want to drag out the issue).

**Comment by kghbln** [comment]
These ones should be cool. I guess we will soon find out via field tests.

**Comment by mwjames** [comment]
>  I guess we will soon find out via field tests.

YES to field tests, that's the way SMW was run in the past.

**Comment by simison** [comment]
Thanks guys.

BTW you haven't published [version tags](https://github.com/SemanticMediaWiki/SemanticWatchlist/releases) for a while and at readme in your example it says `~1.0` — could probably be `*` instead?

**Comment by JeroenDeDauw** [comment]
See #36

**Pull request merged**
