### PR TITLE
Fix 'retrun' typo

### PR DESCRIPTION
**Pull request by zoranzoki21**
Fix 'retrun' typo per task T201491 at Wikimedia Phabricator

### CODE REVIEW

**Comment by kghbln** [comment]
Thank you!

**Comment by zoranzoki21** [comment]
Your welcome. I will resume with contributing.

**Comment by JeroenDeDauw** [comment]
WTF why are you stealing my GitHub avatar?

**Comment by zoranzoki21** [comment]
In which rule is to I no have right to take it?

**Comment by kghbln** [comment]
> In which rule is to I no have right to take it?

There is nobody who forbids you doing it. However if you asked 100 people involved here a minimum of 99 will find it disturbing. Even more so if we take into account that there are millions of avatars around.

**Comment by zoranzoki21** [comment]
I will remove from my profile than.

**Pull request merged**
